framework:
    messenger:
        transports:
            # Disable the Doctrine transport if you don't want the messenger_messages table
            # Use another transport like Redis or RabbitMQ instead
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
